
services:
  test-db:
    image: postgres:16
    container_name: contact_test_db
    env_file: .env
    environment:
      POSTGRES_DB: test_contact
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

    ports:
      - "5434:5432" # mapeo 5433 para el host y 5432 dentro del contenedor.
    volumes:
      - contacto_db_data:/var/lib/postgresql/data
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d contact_test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  contacto_db_data: